export enum TeamStatisticsTitles {
    games = "Games Played",
    fastBreakPoints = "Fast Break Points",
    pointsInPaint = "Points in Paint",
    biggestLead = "Biggest Lead",
    secondChancePoints = "Second Chance Points",
    pointsOffTurnovers = "Points Off Turnovers",
    longestRun = "Longest Run",
    points = "Total Points",
    fgm = "Field Goals Made",
    fga = "Field Goals Attempted",
    fgp = "Field Goal Percentage",
    ftm = "Free Throws Made",
    fta = "Free Throws Attempted",
    ftp = "Free Throw Percentage",
    tpm = "Three Pointers Made",
    tpa = "Three Pointers Attempted",
    tpp = "Three Point Percentage",
    offReb = "Offensive Rebounds",
    defReb = "Defensive Rebounds",
    totReb = "Total Rebounds",
    assists = "Assists",
    pFouls = "Personal Fouls",
    steals = "Steals",
    turnovers = "Turnovers",
    blocks = "Blocks",
    plusMinus = "Plus/Minus"
  }